### PR TITLE
USWDS-Compile - Dependencies: Install optional dependencies for sass-embedded

### LINKED ISSUE #110: USWDS-Compile - Bug: Platform specific sass-embedded modules are missing from package lock
### Describe the bug

This only affects the `develop` branch; it is a regression introduced by #96. Platform specific `sass-embedded` modules are missing for all but `darwin-arm64`. This results in a compilation error when any other platform is used to run `npm run init` after cleanly installing packages.

### Steps to reproduce the bug

Tested on both Windows x64 and Debian 12 x64:

```sh
git checkout develop # reset to match upstream if needed
npm ci
npm run init
```

Error from Windows:
```
npm run init

> @uswds/compile@1.1.0 init
> gulp init

Error: Embedded Dart Sass couldn't find the embedded compiler executable. Please make sure the optional dependency sass-embedded-win32-x64 is installed in node_modules.
```

Error from Linux:
```
npm run init

> @uswds/compile@1.1.0 init
> gulp init

Error: Embedded Dart Sass couldn't find the embedded compiler executable. Please make sure the optional dependency sass-embedded-linux-x64 is installed in node_modules.
```

### Expected Behavior

Compilation should succeed because the platform specific sass-modules are installed.

### Related code

`main` branch: https://github.com/uswds/uswds-compile/blob/6a6b1339099bb3a200a11bc336626f1f5daa3fde/package-lock.json#L4323-L4491

`develop` branch: https://github.com/uswds/uswds-compile/blob/2d7750ad74e84c7e34813870a89ae15d62b1dc5c/package-lock.json#L2636-L2673

### Screenshots

_No response_

### System setup

_No response_

### Additional context

I would normally suggest regenerating `package-lock.json` entirely...
```
rm -rf node_modules/
rm package-lock.json
npm install
```
... but you'd have to be willing to accept any version bumps in other packages that meet the version criteria from `package.json`. So, if that's not acceptable, focus on just `sass-embedded`:
```sh
npm uninstall --save sass-embedded
npm install --save sass-embedded@1.77.5
# edit package.json to remove ^ from version so that it matches the current restriction of using an exact version
npm install
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-compile/issues) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by mahoneycm**
# Summary

Installed optional dependencies for sass-embedded to resolve initialization errors for some systems.

## Related issue

Closes #110 

## Problem statement

Running `npm init` causes an error for some systems where sass-embedded cannot find the correct executable for their system.

## Solution

Install all of `sass-embedded`'s optional dependencies to support other developer machines.

## Testing and review

1. Checkout this branch
2. Run `npm ci`
3. Run `npm run init`
4. Confirm there are no errors

## Dependency updates

No direct dependency updates

### CODE REVIEW

**Comment by mahoneycm** [comment]
Adding comment from @mdmower-csnw in the source issue (#110)

> The updates to `package-lock.json` look complete (matches list of `optionalDependencies` for `sass-embedded`) and I verified I can compile successfully on both Windows 11 64bit and Debian 12 64bit.

**Review by mejiaj — APPROVED** [review]
Thanks Charlie! I can now install and run `npm run init` without errors on win11 x64.

**Review by amyleadem — APPROVED** [review]
Thanks for the quick fix on this @mahoneycm. I was not able to replicate the original issue on my Mac, but I went ahead and performed the test here to confirm that the update in this branch didn't create any new issues for me. It didn't! I was able to run `npm run init` on this branch without error.

**Review by heymatthenry — APPROVED** [review]
